// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axhyoamrmrgtikrvnsrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4aHlvYW1ybXJndGlrcnZuc3JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDkxNTQsImV4cCI6MjA2MDgyNTE1NH0.LmC_M7M-dDGTjDTJfiBMRIcLjbSD_3ZBzQNv62xmAwE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);